[package]
name = "simple"
version = "0.1.0"
edition = "2021"

[dependencies]
block_components = { path = "../../block_components"}
console_error_panic_hook = "0.1.7"
dominator = "0.5.26"
futures-signals = "0.3.28"
once_cell = "1.12.0"
wasm-bindgen = "0.2.74"
wasm-bindgen-futures = "0.4.31"